apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-backend-feed-deployment
  labels:
    app: udagram-backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-backend-feed
  template:
    metadata:
      labels:
        app: udagram-backend-feed
    spec:
      containers:
      - name: udagram-backend_feed
        image: clonck/esiea_projets:udagram-api-feed
        ports:
        - containerPort: 80
