apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-user-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-backend-user
  type: ClusterIP