apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-feed-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-backend-feed
  type: ClusterIP